version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - JWT_SECRET=random_secret
      - SALT_ROUNDS=10
      - DATABASE_PATH="db/dev.sqlite3"
      - SEEDS_PATH="db/seeds"
      - MIGRATION_PATH="db/migrations"
    volumes:
      - ./apps/api/src/db/dev.sqlite3:/usr/src/app/db/dev.sqlite3
    image: api
    ports:
     - "4800:4800"
    restart: always
