version: '3.8'

services:
  api:
    container_name: api
    environment:
      - JWT_SECRET=random_secret
      - SALT_ROUNDS=10
      - DATABASE_PATH="C:/Users/Fabio/OneDrive - students.uninettunouniversity.net/Documenti/Project1/User-dashboard/user-dashboard/apps/api/src/db/dev.sqlite3"
      - SEEDS_PATH="C:/Users/Fabio/OneDrive - students.uninettunouniversity.net/Documenti/Project1/User-dashboard/user-dashboard/apps/api/src/db/seeds"
      - MIGRATION_PATH="C:/Users/Fabio/OneDrive - students.uninettunouniversity.net/Documenti/Project1/User-dashboard/user-dashboard/apps/api/src/db/migrations"
    image: api
    networks:
      - app-network
    ports:
     - "4800:4800"
    restart: always

  app1:
    container_name: app1
    environment:
      - NODE_ENV=development
    image: app1
    networks:
      - app-network
    ports:
      - "5000:5000"
    restart: always
